#!/usr/bin/env python
import sys
import os

try:
    # Intentar importar Nekumo como si formase parte del sistema
    import nekumo
except ImportError:
    # Intentar correr Nekumo como si fuese parte del proyecto (depuración).
    sys.path.append(os.path.split(os.path.dirname(os.path.abspath(__file__)))[0])
    import nekumo


__author__ = 'nekmo'


if __name__ == '__main__':
    os.environ.setdefault("NEKBOT_SETTINGS_MODULE", "settings")

    from nekumo.core.management import Management

    Management().execute()
